server:
  port: 8090

tax-configurations:
  configurations:
    - city: Gothenburg
      rules:
        maximumTaxAmountPerDay: 60
        singleChargePeriod: 60
        timeFeeMapping:
          - startHour: 6
            startMinute: 0
            endHour: 6
            endMinute: 29
            rate: 8
          - startHour: 6
            startMinute: 30
            endHour: 6
            endMinute: 59
            rate: 13
          - startHour: 7
            startMinute: 0
            endHour: 7
            endMinute: 59
            rate: 18
          - startHour: 8
            startMinute: 0
            endHour: 8
            endMinute: 29
            rate: 13
          - startHour: 8
            startMinute: 30
            endHour: 14
            endMinute: 59
            rate: 8
          - startHour: 15
            startMinute: 0
            endHour: 15
            endMinute: 29
            rate: 13
          - startHour: 15
            startMinute: 30
            endHour: 16
            endMinute: 59
            rate: 18
          - startHour: 17
            startMinute: 0
            endHour: 17
            endMinute: 59
            rate: 13
          - startHour: 18
            startMinute: 0
            endHour: 18
            endMinute: 29
            rate: 8
          - startHour: 18
            startMinute: 30
            endHour: 5
            endMinute: 59
            rate: 0
        taxExemptVehicles:
          - MOTORCYCLE
          - BUS
          - TRACTOR
          - EMERGENCY
          - DIPLOMAT
          - FOREIGN
          - MILITARY
        tollFreeDates:
          - 2013-01-01
          - 2013-03-28
          - 2013-03-29
          - 2013-04-01
          - 2013-04-30
          - 2013-05-01
          - 2013-05-08
          - 2013-05-09
          - 2013-06-05
          - 2013-06-06
          - 2013-06-21
          - 2013-07-01
          - 2013-11-01
          - 2013-12-24
          - 2013-12-25
          - 2013-12-26
          - 2013-12-31
